apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v01.api.letsencrypt.org/directory
    email: kyle.tong0609@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production
    http01: {}
