apiVersion: v1
kind: PersistentVolume
metadata:
  name: chartmuseum
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.20.165
    path: /data/k8s













